blank_issues_enabled: false
contact_links:
  - name: Esri Community
    url: https://community.esri.com/t5/esri-leaflet/ct-p/esri-leaflet
    about: Ask questions and discuss with other Esri Leaflet users.
